#!/bin/bash -ex

./flow/frontend/unit . '' flow/mux.unit > ../knit/gen/plan

cd ../knit
invocation=$(cargo run -q run-plan gen/plan ../trailerpark/)

# TODO save to store and symlink. also fix content types
./show-output $invocation out/index.html | ssh calvin.mou.fo 'cat > Public/trailerpark/index.html'

# XXX
# set +x
# echo Open in browser: https://calvin.mou.fo/user/trailerpark/ >&2
# ./graph-production $invocation | dot -Tsvg > gen/trailerpark.svg
# echo Graph: file://$PWD/gen/trailerpark.svg >&2
