#!/bin/bash

pager() {
    if type bat &> /dev/null; then
        git diff-highlight | bat -l diff -p --pager 'less -RFX'
    else
        less -FX
    fi
}

# XXX for demo

if [ $1 = run ]; then
    ./flow/frontend/unit . '' flow/mux.unit > ../knit/gen/plan
    cd ../knit
    trap 'trap - INT' INT
    # stderr redirection loses tty coloring.
    cargo run -q run-plan gen/plan ../trailerpark/ > gen/lastinvocation 2> >(~-/.bin/running-in-place >&2)
    rc=$?
    # XXX doesn't actually check for first run
    if ! grep -q 'nit fetch' ~-/.git/hooks/post-merge 2> /dev/null; then
        echo >&2
        echo -e '  \e[33mNOTICE\e[0m'
        echo 'This appears to be the first nit run in this git repository.' >&2
        echo 'To automatically synchronize with the nit remote, run:' >&2
        echo '$ nit setup-git-hooks' >&2
    fi
    exit $rc
# See https://dvc.org/doc/command-reference/install
elif [ $1 = setup-git-hooks ]; then
    echo -e '#!/bin/bash\n.bin/nit push' > .git/hooks/pre-push
    # Closest we can do to hooking on git fetch
    echo -e '#!/bin/bash\n.bin/nit fetch' > .git/hooks/post-merge
    ln -s post-merge .git/hooks/post-checkout
    chmod +x .git/hooks/pre-push .git/hooks/post-merge
elif [ $1 = push ]; then
    # XXX friendlier output
    exec rsync -a --info=stats ../knit/gen/repo/ joe@calvin.mou.fo:knit-demo/repo
elif [ $1 = fetch ] || [ $1 = pull ]; then
    exec rsync -a --info=stats joe@calvin.mou.fo:knit-demo/repo/ ../knit/gen/repo
elif [ $1 = ls ] || [ $1 = cat ]; then
    shift
    cd ../knit
    exec ./show-output $(<gen/lastinvocation) "$@"
elif [ $1 = graph ]; then
    cd ../knit
    ./graph-production $(<gen/lastinvocation) | dot -Tsvg > gen/trailerpark.svg
    flatpak-spawn --host firefox gen/trailerpark.svg
elif [ $1 = diff ]; then
    shift
    cd ../knit
    cargo run -q diff "$@" | pager
elif [ $1 = scp ]; then
    $0 cat $2 > scp.$$
    scp scp.$$ $3
    rm scp.$$
elif [ $1 = reset ]; then
    set -x
    rm -rf ../knit/gen/repo/ .git/hooks/pre-push .git/hooks/post-merge .git/hooks/post-checkout
    git -C ../knit checkout gen/repo
else
    echo unknown command >&2
    exit 1
fi
